workflow:
    name: 'Pipeline for tag: $CI_COMMIT_TAG'
    rules:
        - if: $CI_COMMIT_TAG

stages:
    - release
    - deploy

release:
    stage: release
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    release:
        tag_name: $CI_COMMIT_TAG
        description: $CI_COMMIT_TAG

pages:
    stage: deploy
    image: node:lts-alpine
    script:
        - npm install
        - npx @11ty/eleventy
    artifacts:
        paths:
            - public
