image: node:16.15.1

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  script:
    - npm install
    - npx @11ty/eleventy
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"