name: Deploy Website

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Load Github repository
        uses: actions/checkout@v4
      - name: Configure Node.js
        uses: actions/setup-node@v4
      - name: Install NPM packages
        run: npm install
      - name: Build Eleventy
        run: npx @11ty/eleventy
      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
